# Site settings
title: fergofrog's blog
description: >-
    fergofrog's blog
baseurl: ""
url: "https://fergofrog.github.io"
twitter_username: fergofrog
github_username:  fergofrog

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
